// This file is generated by Slice Machine. Update with care!

import Image from './Image';
import Introduction from './Introduction';
import Quote from './Quote';
import Text from './Text';
import Title from './Title';

export {
	Image,
	Introduction,
	Quote,
	Text,
	Title,
};

export const components = {
	image: Image,
	introduction: Introduction,
	quote: Quote,
	text: Text,
	title: Title,
};
